AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false
